wgame:
	gcc -Iinclude -Iinclude/sdl2 -Iinclude/headers/network -Iinclude/headers -Llib -o Game src/*.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_net -lSDL2_mixer

mgame: 
	gcc -Iinclude/headers -Iinclude/headers/network src/*.c -o main.o -lSDL2 -lSDL2_image -lSDL2_net -lSDL2_mixer

wserver: 
	gcc -Iinclude -Iinclude/sdl2 -Iserver/headers -Llib -o S server/src/*.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_net

mserver: 
	gcc -Iserver/headers server/src/*.c -o server.o -lSDL2 -lSDL2_net