wgame:
	gcc -Iinclude -Iinclude/sdl -Iinclude/headers -Llib client/*.c -o game.exe src/*.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_net -lSDL2_mixer
mgame: 
	gcc -Iinclude/headers src/*.c client/*.c -o game.exe -lSDL2 -lSDL2_image -lSDL2_net -lSDL2_mixer
mserver: 
	gcc -Iinclude/headers -o S.exe  server/server.c server/networkServer.c  server/udpServer.c server/tcpServer.c -lsdl2 -lsdl2_net
wserver:
	gcc -Iinclude -Iinclude/sdl -Iinclude/headers -Llib -o S.exe  server/server.c server/networkServer.c  server/udpServer.c server/tcpServer.c -lsdl2 -lsdl2_net -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_net -lSDL2_mixer
clear:
	rm *.o *.exe